{% set version = "3.1" %}

package:
  name: imagehash
  version: {{ version }}

source:
  fn: imagehash-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/I/ImageHash/ImageHash-{{ version }}.tar.gz
  sha256: ef6d2d9a8160dff57c2551dfea48b9437d3d674fcb4eaf39623be41c0672dc20

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - numpy
    - scipy
    - pillow
    - pywavelets

test:
  imports:
    - imagehash

about:
  home: https://github.com/JohannesBuchner/imagehash
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Python Perceptual Image Hahsing Module'

extra:
  recipe-maintainers:
    - JohannesBuchner
    - bjlittle
    - ocefpaf
