{% set version = "4.2.0" %}

package:
  name: imagehash
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/I/ImageHash/ImageHash-{{ version }}.tar.gz
  sha256: a969a806cb704a1a88a459a2c53adf87c01b477604b4f25d565cf0f7a49ef14d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - numpy
    - scipy
    - pillow
    - pywavelets

test:
  imports:
    - imagehash

about:
  home: https://github.com/JohannesBuchner/imagehash
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Perceptual Image Hahsing Module

extra:
  recipe-maintainers:
    - JohannesBuchner
    - bjlittle
    - ocefpaf
