{% set name = "imagehash" %}
{% set version = "4.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ImageHash-{{ version }}.tar.gz
  sha256: 7038d1b7f9e0585beb3dd8c0a956f02b95a346c0b5f24a9e8cc03ebadaf0aa70
build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - pillow       # or PIL
    - pywavelets   # for whash
    - scipy        # for phash

test:
  imports:
    - imagehash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JohannesBuchner/imagehash
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Perceptual Image Hahsing Module
  dev_url: https://github.com/JohannesBuchner/imagehash
  doc_url: https://github.com/JohannesBuchner/imagehash/blob/master/README.rst

extra:
  recipe-maintainers:
    - JohannesBuchner
    - bjlittle
    - ocefpaf
