{% set name = "ImageHash" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JohannesBuchner/imagehash/archive/refs/tags/v4.3.2.tar.gz
  sha256: 473f992da754b71ecc61c1fcfd4d4f999a0630a1475fd55e1d572016e043fdae

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pillow
    - numpy
    - scipy
    - pywavelets
    
test:
  source_files:
    - tests
    - README.rst
  imports:
    - imagehash
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest >3
    - six

about:
  home: https://github.com/JohannesBuchner/imagehash
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Perceptual Image Hahsing Module
  description: |
    An image hashing library written in Python.
  dev_url: https://github.com/JohannesBuchner/imagehash
  doc_url: https://github.com/JohannesBuchner/imagehash/blob/master/README.rst

extra:
  recipe-maintainers:
    - JohannesBuchner
    - bjlittle
    - ocefpaf
