travis:
  secure:
    BINSTAR_TOKEN: FU0s/CNpItNFNDkX0aUjk4dUzTxv1K2JXS0KXmA1Kg4+fyH5ofqZ5e+woGSnjJdRzQJuR5Fv7CVoCp5BSbaI7E3MiUR15eqlNaxCdHEup4weMB68iALzhplGkzM5822JvJLDL0rfrj8uPuc5ou1gq12ouKfhyoaVKYiiMZDSiBImAXklrXuTb3xmrBxKEy3hTPTgkYZCGGN09igYbMadPl9LcJN9I3H1XMmbnB8pAC23wAQi8TBkq7VxjHcnBlSxsh2ebgs0+KkzEG8nBlCz9S8BvaVwaUulp866ptau77c6SWWJWFrSFUmywx2uBRzCM9M9V3HdcxmdN7+OfzBQkledVsrAzDGmAS79BNfkD0bNb37w4U9QlPp4IwBuHrGIiskOl5hnAztv3yGf0sQkgjr1HkEHWXqMPHa+Z5ucdJrUAcFrkeqgHSb3WQR43bBXJAddqHxR1ZeJpybkZlnJkUezLzgzwuarurKGN+4mAUWb5sU5+qjru7GK6YpraI7Mz1x4rtN0nP+93c+Bk3/MwG0QSk4107Lz4FSJ7uq69+ndS6w0QSQR7b+Au120N7VwVbSwF4vCJm/FuI2epoWnNpm1nDhEA/LEqJB9C4YJoPBqPqp8fyW4HNyL0nFF/iw2I89zy3MlIBLoVC0c8eNtLcxFiPjANjtUypOanRcntwg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
