travis:
  secure:
    BINSTAR_TOKEN: IiARITRScyurUHi1Y+TxslKkHKtE1/yjyrrarhJfChMjed3xu9P68d48ia2TZw8X3IqcDb8brRSkI5gi8DQvpzwLEQbpGRe5druQtQfejBhMtKiUMktsyGKklUiyfFjWg9/6vs8jefm8+UbG2ykY/a8D97wnpV+H+jww/fV8Z8iKK9TmgEfiY+o07lp5JGBjBW7tZaYnWwxqIWyUxrr6jEqhZbDMQpGjjfEOI9OW0f0AZ7PXJUmkode5ie0gW1dfWZG7dTamWAyaoe1zljYUKYGYkE84VxU1wiKbDYR4oZM1utBKoGEpjYNuHkN8Ksf360ZhgHa5nKkEUwA1XYZY0VLNO5iYE12zHuQZpn72XpssAMkUSpFmEot6O5iuDK5dLNzz2VrBx1WMBe+GUIpMNf0uFY6cm9BXCpyHE6vRFJuZv6+iYoPjqJvN64xV34oQGmZ6fSN3Pa6sluW9Z3/jnffsm4mpksn2KDMAMC1Aj0hk3kVnB6JnwppSzuXgO4KowaMKQd1XajvgJCs2KxlX4TW4PaeqCZOjO7iuJ9EodDf0CE2sjs73eyEXp4FEmoHCx5ttQVed3jLfRPMnfFq9BuROGLbi5lHRVYJpum9BDNZBow1nlNalT99hg/6rteSpEvqynXCGbxzrcCRfwMHvlWpub3uh0+kOxZGVbLcTS9w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
